### PR TITLE
yanderify??

### PR DESCRIPTION
**Pull request by VideoGameSmash12**
lol

### CODE REVIEW

**Comment by Lyicx** [comment]
### fuck i do actually like this but i dont actually want to change the greeter text that drastically smh

**Comment by ayunami2000** [comment]
Looks good. Waiting on @Lyicx to merge.

**Comment by Lyicx** [comment]
> 

no

**Comment by VideoGameSmash12** [comment]
> ### fuck i do actually like this but i dont actually want to change the greeter text that drastically smh

You do realize it's a YandereDev reference, right?

**Comment by Lyicx** [comment]
> You do realize it's a YandereDev reference, right?

i just realised lmfao. you somehow add a toggle to this ill merge it because its lowkey kinda funny

https://fishshell.com/docs/current/language.html

**Comment by literally1984** [comment]
ayornauami when uno point ocho!

**Comment by Lyicx** [comment]
Given my departure with ren, i dont think ill ever reconsider this.

was still a banger message tho

**Pull request closed without merging**
